### ISSUE TITLE
about the output depth image

### ISSUE THREAD

**Issue by skydddive** [pedropro/OMG_Depth_Fusion#1]
hello @pedropro ,your project is amazing ,but i have aquestion about it.i want to save the ouput depth image,but i found the output depth is different with the original one.
the original one:
![1341846314 357937](https://user-images.githubusercontent.com/34952212/54412795-0c7c0480-472f-11e9-9f5c-9fe34f2feb44.png)

the output ond:
![test](https://user-images.githubusercontent.com/34952212/54412665-98d9f780-472e-11e9-8fed-206ae0faa9eb.png)
could you please help me..how to get a similiar output depth with the original one.
because i want to use the output depth fusion to run rgbd-slam, enhancing its perfomance.

**Comment by pedropro** [comment]
Can you post here the code you used to generate/save/show these images, so I can replicate your problem.

**Comment by skydddive** [comment]
> hello @pedropro ,your project is amazing ,but i have aquestion about it.i want to save the ouput depth image,but i found the output depth is different with the original one.
> the original one:
> ![1341846314 357937](https://user-images.githubusercontent.com/34952212/54412795-0c7c0480-472f-11e9-9f5c-9fe34f2feb44.png)
> 
> the output ond:
> ![test](https://user-images.githubusercontent.com/34952212/54412665-98d9f780-472e-11e9-8fed-206ae0faa9eb.png)
> could you please help me..how to get a similiar output depth with the original one.
> because i want to use the output depth fusion to run rgbd-slam, enhancing its perfomance.
